// Collects your followers into a roster file that message.js sends from.
//
//   node harvest.js <your-username> [--target N] [--list followers] [--no-filter]
//
// Kept separate from sending on purpose: re-scrolling a large followers modal from the top is
// slow and Whatnot throttles it (see README, "Stalls vs. the end of the list"). You do not
// want to pay that every day to send 15 messages. Run this occasionally with a big --target;
// message.js then just reads state/<user>-roster.json.
//
// Reruns are additive — already-known usernames are kept in their original order and new ones
// are appended, so message.js works through your followers front to back without repeats.
import { openBrowser, isLoggedIn } from './lib/browser.js';
import * as S from './lib/selectors.js';
import { streamFollowers } from './lib/followerList.js';
import { load, save } from './lib/state.js';

const args = process.argv.slice(2);
const flag = (name, fallback) => {
  const i = args.indexOf(`--${name}`);
  return i === -1 ? fallback : args[i + 1];
};
const flagValues = new Set(args.filter((a) => a.startsWith('--')).map((a) => args[args.indexOf(a) + 1]));

const ME = args.find((a) => !a.startsWith('--') && !flagValues.has(a));
const LIST = flag('list', 'followers') === 'following' ? 'following' : 'followers';
const TARGET = Number(flag('target', 500));
const NO_FILTER = args.includes('--no-filter');

if (!ME) {
  console.error('Usage: node harvest.js <your-username> [--target N]');
  process.exit(1);
}

const STATE_KEY = `${ME}-roster`;
const roster = load(STATE_KEY);
// load() only guarantees { target, results }. Order matters here and object key order is not
// dependable — an all-digit username like "12345" would be reordered as an integer key.
roster.order ??= [];

const known = new Set(roster.order);
const startCount = roster.order.length;
let added = 0;
let skipped = 0;

console.log(`Harvesting ${ME} → ${LIST}   (roster has ${startCount}, adding up to ${TARGET})`);

const context = await openBrowser();
const page = context.pages()[0] ?? (await context.newPage());

await page.route('**/*', (route) => {
  const type = route.request().resourceType();
  return type === 'image' || type === 'media' || type === 'font' ? route.abort() : route.continue();
});

await page.goto(S.profileUrl(ME), { waitUntil: 'domcontentloaded', timeout: 60000 });
await page.waitForTimeout(4000);

if (!(await isLoggedIn(page))) {
  console.error('Not logged in. Run `npm run login` first.');
  await context.close();
  process.exit(1);
}

let stopReason = null;
try {
  const result = await streamFollowers(page, {
    user: ME,
    list: LIST,
    shouldStop: () => added >= TARGET,
    onUsername: (username) => {
      if (known.has(username)) return 'skipped';
      known.add(username);

      if (!NO_FILTER && S.looksAutoGenerated(username)) {
        skipped++;
        return 'skipped';
      }

      roster.order.push(username);
      added++;
      if (added % 25 === 0) {
        console.log(`  … ${added} new (${roster.order.length} total)`);
        save(roster); // checkpoint, so a crash doesn't cost the whole scroll
      }
      return added >= TARGET ? 'stop' : 'queued';
    },
  });
  stopReason = result.stopReason;
} catch (err) {
  stopReason = `Crashed: ${err?.message?.split('\n')[0] ?? err} — rerun to continue`;
}

save(roster);

console.log(`\n──────── ${stopReason ?? (added >= TARGET ? `Reached target of ${TARGET}` : 'Done')} ────────`);
console.log(`  new usernames:    ${added}`);
console.log(`  skipped (junk):   ${skipped}`);
console.log(`  roster total:     ${roster.order.length}`);
console.log(`  state: state/${STATE_KEY}.json`);

await context.close();
