// Every Whatnot-specific DOM assumption lives here. If Whatnot redesigns,
// this is the only file that should need changing.
//
// Verified live 2026-07-20 (logged out):
//   - Profile page: https://www.whatnot.com/user/<username>  (200 only in a headed browser;
//     headless trips a Cloudflare challenge)
//   - There is NO /user/<username>/followers or /following route — both 404. Each list is a
//     modal opened by a <button> on the profile, e.g. "25K Followers" / "305.4K Following".
//   - A profile-level "Follow" <button> exists for the profile owner.
//   - The modal's internals require a logged-in session to inspect.

export const BASE_URL = 'https://www.whatnot.com';

// Clicking Follow fires this GraphQL mutation. Its response is the ONLY trustworthy
// confirmation: the button itself flips optimistically on click, so a throttled/rejected
// follow still renders as "Following" until the page is reloaded.
//   {"data":{"followUser":{"success":true,"user":{"isFollowing":true}}}}
export const FOLLOW_MUTATION_URL = 'operationName=FollowUser';

export function followMutationSucceeded(json) {
  const r = json?.data?.followUser;
  return r?.success === true && r?.user?.isFollowing === true;
}

export const profileUrl = (username) => `${BASE_URL}/user/${username}`;

// The "N Followers" / "N Following" buttons on a profile. Anchored to the trailing word
// so they can't match the profile's own "Follow" / "Following" action button.
export const listTabButton = (page, list) =>
  page.getByRole('button', { name: list === 'followers' ? /\bFollowers$/ : /\bFollowing$/ }).first();

// The count baked into those buttons: "25K Followers" → 25000, "305.4K Following" → 305400,
// "598 Followers" → 598. Whatnot rounds these, so the result is approximate and should only
// ever be compared loosely — it exists to tell "the list ended" apart from "the list stopped
// serving rows", never to decide that work is complete.
export function parseListCount(label) {
  const m = /([\d.,]+)\s*([KM]?)\s*(?:followers|following)/i.exec(label ?? '');
  if (!m) return null;
  const n = Number(m[1].replace(/,/g, ''));
  if (!Number.isFinite(n)) return null;
  const mult = m[2].toUpperCase() === 'M' ? 1e6 : m[2].toUpperCase() === 'K' ? 1e3 : 1;
  return Math.round(n * mult);
}

// The modal that opens as a result.
export const listDialog = (page) => page.locator('[role="dialog"]').last();

// A row's user link inside the modal. Whatnot uses hashed class names, so rows are
// identified by the /user/<name> anchor they contain rather than by class.
export const userLinks = (scope) => scope.locator('a[href^="/user/"]');

// Follow / Following action buttons. Exact-match so "Following" never matches "Follow".
export const followButton = (scope) => scope.getByRole('button', { name: /^Follow$/ });
export const followingButton = (scope) => scope.getByRole('button', { name: /^Following$/ });

// Text that means "this account already follows them".
export const FOLLOWED_RE = /^following$/i;

// Whatnot's follower lists are sorted ascending by username, so the head of the list is
// dominated by auto-generated / throwaway accounts (e.g. "___________0",
// "00000000000000000000000000_tex"). These are worthless to follow, so skip them.
export function looksAutoGenerated(username) {
  const u = username.toLowerCase();

  // Long leading run of underscores or digits, e.g. "0000000000000accessthegold".
  // Threshold is 6 so real handles that merely start with a year ("2024cards") survive.
  if (/^[_\d]{6,}/.test(u)) return true;

  // Any long run of one repeated character anywhere.
  if (/(.)\1{5,}/.test(u)) return true;

  // Majority of the name is digits/underscores. Only applied to longer names — short
  // real handles ("mj_23", "kj23") are legitimately digit-heavy.
  const junk = (u.match(/[_\d]/g) ?? []).length;
  if (u.length >= 8 && junk / u.length > 0.5) return true;

  // Essentially no letters at all. Kept loose so short real handles ("kj23") survive.
  if ((u.match(/[a-z]/g) ?? []).length < 2) return true;

  return false;
}

export const usernameFromHref = (href) => {
  const m = /^\/user\/([^/?#]+)/.exec(href ?? '');
  return m ? m[1] : null;
};
